apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: inno-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      enableServiceLinks: false
      containers:
        - name: order-service
          image: artorient/order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: ORDER_DB_HOST
              value: "postgres"
            - name: ORDER_DB_PORT
              value: "5432"
            - name: ORDER_DB_NAME
              value: "orderdb"
            - name: ORDER_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: ORDER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20