apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: inno-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      enableServiceLinks: false
      containers:
        - name: user-service
          image: artorient/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            # --- DATABASE ---
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "userdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            # --- REDIS ---
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

            # --- JWT ---
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10